### ISSUE TITLE
Unexpected behaviour when query ends with a space

### ISSUE THREAD

**Issue by moroshko** [joshjung/trie-search#1]
Consider the following example:

    var TrieSearch = require('trie-search');
    var trie = new TrieSearch(['name', 'city']);

    trie.add({ name: 'a b', city: 'c' });
    trie.add({ name: 'd', city: 'c' });

    console.log(trie.get('a ')); // => [ { name: 'a b', city: 'c' }, { name: 'd', city: 'c' } ]

Why `{ name: 'd', city: 'c' }` is found?

**Comment by joshjung** [comment]
Just noticed this issue. For some reason I do not remember receiving any email about this. I'll take a look tomorrow! You did not happen to find a fix since you posted this did you?

**Comment by moroshko** [comment]
@joshjung Not yet. Will appreciate if you could check what's wrong. Thanks!

**Comment by joshjung** [comment]
Check out the fix I just checked in. I've tested it via unit test and all seems to be working as expected.

By default the Trie treats whitespace as a delimiter. Set `options.splitOnRegEx` property to `false`. This will keep it the Trie splitting all keys based on whitespace. Please note, however, that the phrases that are passed into the `get(phrases)` method will need to be manually split to get the effect of an OR operation now. This is what I imagine will be an edge case in your scenario though.

**Comment by moroshko** [comment]
Thanks for the fix :+1:
