### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by UKNC** [joshjung/trie-search#15]
It would be great to have the defs.

**Comment by joshjung** [comment]
Hey there @UKNC this is a really great idea. I'm not sure I will have time in the near future to do this since my workload is pretty high lately, but if you are interested in contributing you could either make a PR or add definitions to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by chetbox** [comment]
For now, see #30 for a Typescript fork.

**Comment by joshjung** [comment]
TypeScript definitions have now been added.
