### ISSUE TITLE
get returns undefined

### ISSUE THREAD

**Issue by jmarroyave** [joshjung/trie-search#20]
Hi Josh, 

When the key is 'constructor' the function get throws an error

> TypeError: Cannot read property 'length' of undefined  at JClass.addAll (/scripts/node_modules/hasharray/src/HashArray.js:70:13)
>  at TrieSearch.get (/scripts/node_modules/trie-search/src/TrieSearch.js:314:70)

after debugging the problem was in the function _get in the getCache to be more precise

```
  _get: function (phrase) {
    phrase = this.options.ignoreCase ? phrase.toLowerCase() : phrase;
    
    var c, node;
    if (this.options.cache && (c = this.getCache.get(phrase))){
      return c.value
    }
```
i changed it to this 

```
  _get: function (phrase) {
    phrase = this.options.ignoreCase ? phrase.toLowerCase() : phrase;
    
    var c, node;
    if (this.options.cache && this.getCache.has(phrase)){
      return this.getCache.get(phrase).value;
    }
```
the problem is in the this.getCache.get implementation. 

Thanks in advance

**Comment by joshjung** [comment]
Feel free to make a PR and a test and I'll merge it in!

**Comment by jmarroyave** [comment]
Thanks, but this is just a work around, the problem is in the hash array implementation.
