### ISSUE TITLE
Search in any position of words

### ISSUE THREAD

**Issue by ViieeS** [joshjung/trie-search#24]
For the term `ob` and the given object array:

```
const names = [
  {name: 'bill', age: 35},
  {name: 'billy', age: 35},
  {name: 'bob', age: 35},
  {name: 'bobby', age: 22},
  {name: 'bo', age: 35}
];
```

I'd like to get the result:

```
[
 {name: 'bob', age: 35},
 {name: 'bob', age: 15},
]
```

Is it possible now?

**Comment by joshjung** [comment]
It is definitely **possible**.

But at this time this is not possible with this library, as this is not a part of the original Trie algorithm spec. It could be a possible option that gets turned on, I suppose, if someone would want to make a PR for this. My main concern would be that insertion times for large keys would get slow and memory would balloon to be unreasonable for large search sets.

I might check out something like this instead: https://www.npmjs.com/package/@lokidb/full-text-search

Or if you need something really beefy with a backend, definitely look into Lucid search.
