### ISSUE TITLE
Is there is a way to update object by its unique Id?

### ISSUE THREAD

**Issue by MarkZaki** [joshjung/trie-search#25]
Is there is a way to update object by its unique Id?
after searching in docs, I can't find anything

**Comment by joshjung** [comment]
Hey there @MarkZaki. This would involve the removal of the existing mappings and then a reinsert of the object. This could be added and optimized, but does not exist right now. I will look into this, but no promises. Rebuilding the trie might be easier. What size is your trie? Are you making changes to the keys often?

**Comment by MarkZaki** [comment]
I've found a way to manage that, 
I search the tree with the index field and update the object based on that, since the objects are passed by reference, thanks

**Comment by joshjung** [comment]
Oh this is a great idea @MarkZaki. If it is working well, feel free to submit a PR with that added to the README and I will get it in for everyone else :D
