### ISSUE TITLE
Problem passing an Array of Strings, takes only the first value.

### ISSUE THREAD

**Issue by wokung** [joshjung/trie-search#27]
Hi,

I have a structure like this:

`
categories:
[
  0: Object
    name: "Test",
    synonyms: ["Hello", "Nice", "String"]
  1: Object
    name: "Susi",
    synonyms: ["Peter", "Betti", "Christian"]
   ...
   ...
]
`

So I created a TrieSearch with:

`new TrieSearch(['name', ['synonyms']], { min: 3 }),` 

`
ts.addAll(categories);
`

However, with ts.get() I only receive the first index of synonyms.

So, ts.get("Hello") will give me the value of index 0 of categories.

But with ts.get("Nice") I won't get anything.

Am I missing something here?

I hope someone can help me.

**Comment by cesRay** [comment]
I have the same issue! I'm trying to search through an object array for a key that has an array as its value, let's say: 
`people = [ { name: 'Richard', hobbies: ['Skating', 'Watch Movies'] },
                  { name: 'Bryan', hobbies: ['Skip school', 'Being a total ass'] }
                 ]`

So when trying to look for 'Richard' by typing 'Skating', works just fine. But typing 'Watch Movies' doesn't work. Just like @wokung said, it takes only the first value. Is there any way `ts.get()`can account for all the positions in the array? Or is there any other method besides `ts.get()` we could use?

**Comment by joshjung** [comment]
Sorry for such a late reply on this. I did not build the Trie Search to manually search through arrays like that. My recommendation would be to manually add the mappings like so:

```
const ts  = new TrieSearch('someKey');

items.forEach(item => {
  ts.add(item);

  item.hobbies.forEach(hobby => {
    ts.map(hobby, item);
  });
});
```
