### ISSUE TITLE
Issue with matching last word in a sentence

### ISSUE THREAD

**Issue by nosisky** [joshjung/trie-search#41]
Hello,
Great job on this library, I appreciate the work so far. I am having some issues with matching the last word in a sentence.

For example:
`
const optionsArray = [
  'Hello world',
  'Sample test'
];

const trie = new TrieSearch([], { splitOnRegEx: false });

optionsArray.forEach((item) => {
  trie.map(item, item);
});

`

Searching for **world** or **test** returns 0 results, how can I fix this?

trie.search('world') --> null
trie.search('test') --> null

trie.search('hello') --> Hello world

**Comment by nosisky** [comment]
@joshjung any idea on how to resolve this?

**Comment by joshjung** [comment]
Was there a special reason that you did not want to Split on a Regular Expression? The purpose of splitting on a regular expression is to take a sentence like yours and split it along word boundaries so that each word can be searched independently.
